### ISSUE TITLE
 High GPU Memory Usage in `create_feature_field_lseg` Function in transfer.py

### ISSUE THREAD

**Issue by jannick-schroeer** [JojiJoseph/3dgs-gradient-backprojection#1]
## Description
The `create_feature_field_lseg` function in the repository encounters a GPU memory allocation issue when running on certain hardware configurations. Specifically, the following error is observed:

```bash
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.08 GiB. GPU 0 has a total capacity of 15.70 GiB of which 1.26 GiB is free. Including non-PyTorch memory, this process has 13.87 GiB memory in use. Of the allocated memory 13.41 GiB is allocated by PyTorch, and 282.69 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

This occurs due to the high memory requirements of the `LSegNet` model during the processing of feature backprojection.

## Affected Code
The specific code block that triggers this issue is:

```python
net = LSegNet(
    backbone="clip_vitl16_384",
    features=256,
    crop_size=480,
    arch_option=0,
    block_depth=0,
    activation="lrelu",
)
# Load pre-trained weights
net.load_state_dict(torch.load("./checkpoints/lseg_minimal_e200.ckpt"))
net.eval()
net.cuda()
```

The memory-intensive operation further propagates during the loop over `colmap_project.images.values()` when repeatedly invoking rasterization and the forward pass of `LSegNet`.

## System Configuration
- **CPU**: AMD Ryzen 7 3800X
- **RAM**: 32 GB
- **GPU**: NVIDIA RTX 4060 Ti (16 GB VRAM)

## Proposed Solution
I have identified a solution to optimize GPU memory usage, which I will include in a forthcoming PR. The changes involve:
- Adding the option to run the function on the CPU
- Adding batches
- Clearing Cache and unused variables in between iterations

## Steps to Reproduce
1. Run the `create_feature_field_lseg` function on a system with a similar GPU memory configuration.
2. Use a dataset with a significant number of images and large feature dimensions.

## Expected Behavior
The function should run without exceeding GPU memory limits, even on GPUs with 16 GB of VRAM.

## Actual Behavior
The process fails with `torch.cuda.OutOfMemoryError`.

## Next Steps
- Submit a PR with the proposed solution.
- Update the documentation to include recommendations for hardware requirements and memory management strategies.

---

Please let me know if additional details or benchmarks are required!

**Comment by JojiJoseph** [comment]
Merged. Thanks!
